=== ubc-magic/CoffeeShop/JavaSource/ca/ubc/magic/coffeeshop/config/application.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
            xmlns="http://pspi.magic.ubc.ca"
            targetNamespace="http://pspi.magic.ubc.ca"
            elementFormDefault="qualified"
            jxb:version="2.0">

<xsd:complexType name="application">
  <xsd:sequence>
    <xsd:element name="applicationName" type="xsd:string" nillable="false" maxOccurs="1"/>
    <xsd:element name="applicationShortName" type="xsd:string" nillable="false" maxOccurs="1"/>
    <xsd:element name="applicationImageURL" type="xsd:string" nillable="false" maxOccurs="1"/>
    <xsd:element name="minumumIdleTime" type="xsd:int" nillable="false" maxOccurs="1"/>
    <xsd:element name="applicationDescription" type="xsd:string" minOccurs="0" maxOccurs="1"/>
    <xsd:element name="interactionInstructions" type="xsd:string" minOccurs="0" maxOccurs="1"/>
    <xsd:element name="connectionInfo" type="connection" nillable="false"/>
    <xsd:element name="parameters" type="parameters" minOccurs="0" maxOccurs="1"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="connection">
	<xsd:sequence>
		<xsd:element name="topic" type="xsd:string" nillable="false" maxOccurs="1"/>
		<xsd:element name="displayURL" type="xsd:string" minOccurs="0"/>
		<xsd:element name="connectorClass" type="xsd:string" minOccurs="1" default="ca.ubc.magic.coffeeshop.connectors.DefaultConnector"/>
	</xsd:sequence>
	<xsd:attribute name="applicationType" use="required">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="web"/>
				<xsd:enumeration value="swf"/>
		    </xsd:restriction>
	    </xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="useFullScreen" use="required">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="true"/>
				<xsd:enumeration value="false"/>
		    </xsd:restriction>
		   </xsd:simpleType>
	</xsd:attribute>
</xsd:complexType>

<xsd:complexType name="parameters">
	<xsd:sequence>
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
	    	<xsd:element name="textbox" type="textbox"/>
			<xsd:element name="textarea" type="textarea"/>
			<xsd:element name="password" type="password"/>
			<xsd:element name="radioList" type="radioList"/>
			<xsd:element name="checkboxList" type="checkboxList"/>
			<xsd:element name="listbox" type="listbox"/>
	    </xsd:choice>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="parameter">
	<xsd:sequence>
		<xsd:element name="order" type="xsd:int" minOccurs="1" maxOccurs="1"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="textbox">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="textarea">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="password">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="radioList">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="checkboxList">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="listbox">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:element name="pluginApp" type="application"/>

</xsd:schema>

=== ubc-magic/CoffeeShop/WebContent/WEB-INF/classes/ca/ubc/magic/coffeeshop/config/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Directory</applicationName>
    <applicationShortName>directory</applicationShortName>
    <applicationImageURL>http://kimberly.magic.ubc.ca:8080/CoffeeShop/img/directory.png</applicationImageURL>
    <minumumIdleTime>20</minumumIdleTime>
    
    <applicationDescription>The following is a proposed application to explore direct and indirect mobile phone to large public display interaction in an informational domain for Goal B of the Public Spaces and Personal Interaction (PSPI) project. The application proposed is a large public directory like that of a shopping mall directory, but interactive. Our application aims to be a city directory, listing shops, stores and facilities around downtown Vancouver, which we call venues.</applicationDescription>
    
    <interactionInstructions>Click the Flash application to ensure it is focused 
    Press the ` key (under the tilde key) on your keyboard to bring up the console
    Type "1,new" (no spaces) into the console to join the application
    Use the following console commands to interact:
    "1,up" to move up
    "1,down" to move down
    "1,left" to move left
    "1,right" to move right
    "1,select" to make a selection
    "1,back" to deselect/go back
    "1,remove" to disconnect/remove the user
    "1,reset" to reset the user
    "ld" to enable LD mode
    "ldsd" to enable LDSD mode
    "in" to zoom in one level
    "out" to zoom out one level</interactionInstructions>
    <connectionInfo applicationType="web" useFullScreen="false">
        <topic>cs_idirectory</topic>
        <displayURL>http://pspi.magic.ubc.ca:8080/IDirectory/</displayURL>
        <connectorClass>ca.ubc.magic.coffeeshop.connectors.IdirectoryConnector</connectorClass>
    </connectionInfo>
    
</pluginApp>

=== ubc-magic/CoffeeShop/JavaSource/ca/ubc/magic/coffeeshop/config/socialcapital.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Social Capital</applicationName>
    <applicationShortName>socialcapital</applicationShortName>
    <applicationImageURL>http://kimberly.magic.ubc.ca:8080/CoffeeShop/img/socialwall.png</applicationImageURL>
    <minumumIdleTime>20</minumumIdleTime>
    
    <applicationDescription>This application lets you interact with people in your community.</applicationDescription>
    <interactionInstructions>You need to send messages through twitter.</interactionInstructions>
    
    <connectionInfo applicationType="web" useFullScreen="false">
        <topic>cs_socialwall</topic>
        <displayURL>http://kimberly.magic.ubc.ca/social-capital-viz/index.html</displayURL>
        <connectorClass>ca.ubc.magic.coffeeshop.connectors.SocialCapitalConnector</connectorClass>
    </connectionInfo>
    
</pluginApp>

=== ubc-magic/CoffeeShop/WebContent/WEB-INF/classes/ca/ubc/magic/coffeeshop/config/splash.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Splash!</applicationName>
    <applicationShortName>splash</applicationShortName>
    <applicationImageURL>http://people.rit.edu/andpph/photofile-c/splash-4.jpg</applicationImageURL>
    <minumumIdleTime>10</minumumIdleTime>
    
    <applicationDescription>The pet of our application.</applicationDescription>
    
    <connectionInfo applicationType="web" useFullScreen="false">
        <topic>cs_splash</topic>
        <displayURL>http://redhead.magic.ubc.ca/index.html</displayURL>
        <connectorClass></connectorClass>
    </connectionInfo>
    
</pluginApp>
