=== ubc-magic/CoffeeShop/JavaSource/ca/ubc/magic/coffeeshop/config/application.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
            xmlns="http://pspi.magic.ubc.ca"
            targetNamespace="http://pspi.magic.ubc.ca"
            elementFormDefault="qualified"
            jxb:version="2.0">

<xsd:complexType name="application">
  <xsd:sequence>
    <xsd:element name="applicationName" type="xsd:string" nillable="false" maxOccurs="1"/>
    <xsd:element name="applicationShortName" type="xsd:string" nillable="false" maxOccurs="1"/>
    <xsd:element name="applicationImageURL" type="xsd:string" nillable="false" maxOccurs="1"/>
    <xsd:element name="minumumIdleTime" type="xsd:int" nillable="false" maxOccurs="1"/>
    <xsd:element name="applicationDescription" type="xsd:string" minOccurs="0" maxOccurs="1"/>
    <xsd:element name="interactionInstructions" type="xsd:string" minOccurs="0" maxOccurs="1"/>
    <xsd:element name="connectionInfo" type="connection" nillable="false"/>
    <xsd:element name="parameters" type="parameters" minOccurs="0" maxOccurs="1"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="connection">
	<xsd:sequence>
		<xsd:element name="topic" type="xsd:string" nillable="false" maxOccurs="1"/>
		<xsd:element name="displayURL" type="xsd:string" minOccurs="0"/>
		<xsd:element name="connectorClass" type="xsd:string" minOccurs="1" default="ca.ubc.magic.coffeeshop.connectors.DefaultConnector"/>
	</xsd:sequence>
	<xsd:attribute name="applicationType" use="required">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="web"/>
				<xsd:enumeration value="swf"/>
		    </xsd:restriction>
	    </xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="useFullScreen" use="required">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="true"/>
				<xsd:enumeration value="false"/>
		    </xsd:restriction>
		   </xsd:simpleType>
	</xsd:attribute>
</xsd:complexType>

<xsd:complexType name="parameters">
	<xsd:sequence>
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
	    	<xsd:element name="textbox" type="textbox"/>
			<xsd:element name="textarea" type="textarea"/>
			<xsd:element name="password" type="password"/>
			<xsd:element name="radioList" type="radioList"/>
			<xsd:element name="checkboxList" type="checkboxList"/>
			<xsd:element name="listbox" type="listbox"/>
	    </xsd:choice>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="parameter">
	<xsd:sequence>
		<xsd:element name="order" type="xsd:int" minOccurs="1" maxOccurs="1"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="textbox">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="textarea">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="password">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="radioList">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="checkboxList">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="listbox">
	<xsd:complexContent>
		<xsd:extension base="parameter">
			<xsd:sequence>
				<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:extension>
	</xsd:complexContent>
</xsd:complexType>

<xsd:element name="pluginApp" type="application"/>

</xsd:schema>

=== ubc-magic/CoffeeShop/WebContent/WEB-INF/classes/ca/ubc/magic/coffeeshop/config/counter.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Counter</applicationName>
    <applicationShortName>counter</applicationShortName>
    <applicationImageURL>http://localhost/counter/counter.png</applicationImageURL>
    <minumumIdleTime>20</minumumIdleTime>
    
    <applicationDescription>This application is a sample application.</applicationDescription>
    <interactionInstructions>Visit the Large-Mobile guide.</interactionInstructions>
    
    <connectionInfo applicationType="web" useFullScreen="false">
        <topic>hello</topic>
        <displayURL>http://localhost/counter/large/index.html</displayURL>
        <connectorClass>ca.ubc.magic.coffeeshop.connectors.CounterConnector</connectorClass>
    </connectionInfo>
    
</pluginApp>

=== ubc-magic/CoffeeShop/WebContent/WEB-INF/classes/ca/ubc/magic/coffeeshop/config/hello.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Hello World</applicationName>
    <applicationShortName>hello</applicationShortName>
    <applicationImageURL>http://localhost/hello/hello.png</applicationImageURL>
    <minumumIdleTime>20</minumumIdleTime>
    
    <applicationDescription>This application is a sample application.</applicationDescription>
    <interactionInstructions>Visit the Getting Started guide.</interactionInstructions>
    
    <connectionInfo applicationType="web" useFullScreen="false">
        <topic>hello</topic>
        <displayURL>http://localhost/hello/index.html</displayURL>
        <connectorClass>ca.ubc.magic.coffeeshop.connectors.HelloConnector</connectorClass>
    </connectionInfo>
    
</pluginApp>

=== ubc-magic/CoffeeShop/WebContent/WEB-INF/classes/ca/ubc/magic/coffeeshop/config/magicbeans.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Magic Beans</applicationName>
    <applicationShortName>magicbeans</applicationShortName>
    <applicationImageURL>http://kimberly.magic.ubc.ca:8080/CoffeeShop/img/magicbeans.png</applicationImageURL>
    <minumumIdleTime>20</minumumIdleTime>
    
    <applicationDescription>This application lets you interact with people in your community.</applicationDescription>
    <interactionInstructions>You need to visit beans.icd.magic.ubc.ca</interactionInstructions>
    
    <connectionInfo applicationType="web" useFullScreen="false">
        <topic>cs_magicbeans</topic>
        <displayURL>http://kimberly.magic.ubc.ca/ld/index.html</displayURL>
        <connectorClass>ca.ubc.magic.coffeeshop.connectors.MagicBeansConnector</connectorClass>
    </connectionInfo>
    
</pluginApp>

=== ubc-magic/CoffeeShop/JavaSource/ca/ubc/magic/coffeeshop/config/eyeballing.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Eye Ball</applicationName>
    <applicationShortName>eyeballing</applicationShortName>
    <applicationImageURL>http://kimberly.magic.ubc.ca:8080/CoffeeShop/img/eyeballing.png</applicationImageURL>
    <minumumIdleTime>10</minumumIdleTime>
    
    <applicationDescription>This game helps us study whether uses prefer doing fine granularity interactions on the large display or on the small display by making users nudge an on screen marker to perform a specified task such as finding the mid point of a line, or adjusting some edges of a shape to make it a parallelogram.</applicationDescription>
    <interactionInstructions>You will need to download the phone client here: http://www.somebogusurl.com/
    This phone client is a Flash Lite 3.0 program wrapped in Adobe's Mobile Packager and has only been tested for the Nokia N95 (both versions of the Nokia N95)
    To change the mode the parent application is in, right click on the Flash application and select "Set xx Mode" where xx is the mode you would like to set the parent application to, note that this does not persist so you need to set it everytime, the default mode is LD mode
    You can check the mode after setting it by hovering your mouse over the bottom right hand corner of the application - where there is a little flap
    </interactionInstructions>
    
    <connectionInfo applicationType="web" useFullScreen="true">
        <topic>cs_eyeball</topic>
        <displayURL>http://pspi.magic.ubc.ca:8080/EyeballingGame/</displayURL>
        <connectorClass>ca.ubc.magic.coffeeshop.connectors.EyeballingConnector</connectorClass>
    </connectionInfo>
    
</pluginApp>

=== ubc-magic/CoffeeShop/JavaSource/ca/ubc/magic/coffeeshop/config/bomberman_swf.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Bomberman</applicationName>
    <applicationShortName>bomberman_swf</applicationShortName>
    <applicationImageURL>http://kimberly.magic.ubc.ca:8080/CoffeeShop/img/bomberman.png</applicationImageURL>
    <minumumIdleTime>30</minumumIdleTime>
    
    <applicationDescription>This is a description of the bomberman application.  You can use this as you would any application currently deployed</applicationDescription>
    <interactionInstructions>You need to do stuff with this application.</interactionInstructions>
    <connectionInfo applicationType="web" useFullScreen="false">
        <topic>cs_bomberman_swf</topic>
        <displayURL>http://pspi.magic.ubc.ca:8080/Bomberman/</displayURL>
        <connectorClass></connectorClass>
    </connectionInfo>
  
</pluginApp>

=== ubc-magic/CoffeeShop/JavaSource/ca/ubc/magic/coffeeshop/config/contexty.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Contexty</applicationName>
    <applicationShortName>contexty</applicationShortName>
    <applicationImageURL>http://kimberly.magic.ubc.ca:8080/CoffeeShop/img/video.png</applicationImageURL>
    <minumumIdleTime>60</minumumIdleTime>
    
    <applicationDescription>Contextual ambient information..</applicationDescription>
    
    <connectionInfo applicationType="web" useFullScreen="false">
        <topic>cs_contexty</topic>
        <displayURL>http://kimberly.magic.ubc.ca/contexty/index.html</displayURL>
        <connectorClass></connectorClass>
    </connectionInfo>
    
</pluginApp>

=== ubc-magic/CoffeeShop/WebContent/WEB-INF/classes/ca/ubc/magic/coffeeshop/config/videowall.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Video Wall</applicationName>
    <applicationShortName>videowall</applicationShortName>
    <applicationImageURL>http://kimberly.magic.ubc.ca:8080/CoffeeShop/img/video.png</applicationImageURL>
    <minumumIdleTime>10</minumumIdleTime>
    <connectionInfo applicationType="web" useFullScreen="false">
        <topic>cs_videowall</topic>
        <displayURL>http://pspi.magic.ubc.ca:8080/VideoWallLDSD/VideoWallLDSD.swf</displayURL>
        <connectorClass></connectorClass>
    </connectionInfo>
    
</pluginApp>

=== ubc-magic/CoffeeShop/WebContent/WEB-INF/classes/ca/ubc/magic/coffeeshop/config/bomberman_web.xml
<?xml version="1.0" encoding="UTF-8"?>
<pluginApp xmlns="http://pspi.magic.ubc.ca"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pspi.magic.ubc.ca application.xsd">
           
    <applicationName>Bomberman</applicationName>
    <applicationShortName>bomberman_web</applicationShortName>
    <applicationImageURL>http://kimberly.magic.ubc.ca:8080/CoffeeShop/img/bomberman.png</applicationImageURL>
    <minumumIdleTime>30</minumumIdleTime>
    <connectionInfo applicationType="web" useFullScreen="false">
        <topic>cs_bomberman_swf</topic>
        <displayURL>http://pspi.magic.ubc.ca:8080/Bomberman/</displayURL>
        <connectorClass></connectorClass>
    </connectionInfo>

    
</pluginApp>
